class Constants:
    '''
    常量
    '''

    #常量
    UNDEFINED_NUMBER = -1
    MAX_NUMBER = 1145141919810
    
    MIN_MAX_USER = 3

    #活动状态
    ACTIVITY_STATUS_GLOBAL_EXCEPT = 0
    ACTIVITY_STATUS_GLOBAL_NORMAL = 1
    ACTIVITY_STATUS_GLOBAL_FINISH = 2
    ACTIVITY_STATUS_GLOBAL_AUDIT = 3
    ACTIVITY_STATUS_JOIN_BEFORE = 0
    ACTIVITY_STATUS_JOIN_CONTINUE = 1
    ACTIVITY_STATUS_JOIN_PAUSED = 2
    ACTIVITY_STATUS_JOIN_STOPPED = 3
    ACTIVITY_STATUS_CHECK_BEFORE = 0
    ACTIVITY_STATUS_CHECK_CONTINUE = 1
    ACTIVITY_STATUS_CHECK_PAUSED = 2
    ACTIVITY_STATUS_CHECK_STOPPED = 3

    #用户状态
    USER_STATUS_NOT_JOINED = -1
    USER_STATUS_WAITVALIDATE = 0
    USER_STATUS_JOINED = 1
    USER_STATUS_CHECKED = 2
    USER_STATUS_FINISHED = 3
    USER_STATUS_FINISHED_WITHOUT_CHECK = 4
    USER_STATUS_ABNORMAL = 5
    USER_STATUS_REFUSED = 6

    #用户权限
    USER_ROLE_COMMONER = 0
    USER_ROLE_MANAGER = 1
    USER_ROLE_CREATOR = 2

    #错误码
    ERROR_CODE_NOT_STORED = 101
    ERROR_CODE_RECOMMEND = 201
    ERROR_CODE_NO_REASON = 211
    ERROR_CODE_REJECT = 212
    ERROR_CODE_UNKNOWN = 500
    ERROR_CODE_LOGIN_ERROR = 501
    ERROR_CODE_INVALID_PARAMETER = 502
    ERROR_CODE_NOT_FOUND = 503
    ERROR_CODE_INVALID_CHANGE = 504
    ERROR_CODE_LACK_ACCESS = 505
    ERROR_CODE_NETWORK_ERROR = 506
    ERROR_CODE_DENIAL = 507

    #规则类型
    GLOBAL_RULE_ACCEPT = 0
    GLOBAL_RULE_AUDIT = 1
    GLOBAL_RULE_REJECT = 2

    ADVANCED_RULE_ACCEPT = 0
    ADVANCED_RULE_AUDIT = 1
    ADVANCED_RULE_REJECT = 2

    #推荐
    MAX_RECOMMEND_WORD = 20


    #消息推送的常量定义
    MESSAGE_TYPE_KICK = 0
    MESSAGE_TYPE_AUDIT_PASS = 1
    MESSAGE_TYPE_AUDIT_FAIL = 2
    MESSAGE_TYPE_ACTIVITY_CANCEL = 3
    MESSAGE_TYPE_ACTIVITY_FORBIDDEN = 4
    MESSAGE_TYPE_ACTIVITY_CHANGE = 5
    MESSAGE_TYPE_ACTIVITY_WILL_START_HOUR = 6
    MESSAGE_TYPE_ACTIVITY_WILL_START_MINUTE = 7
    MESSAGE_TYPE_NEW_ACTIVITY_PASS = 8
    MESSAGE_TYPE_NEW_ACTIVITY_FAIL = 9

    #推送提前时间的常量定义（单位秒）
    TIME_BEFORE_MESSAGE_ACTIVITY_WILL_START_HOUR = 86400
    TIME_BEFORE_MESSAGE_ACTIVITY_WILL_START_MINUTE = 7200

    #签到的常量定义
    SUCCESS_THRESHOLD = 100

    #积分常量定义
    SUCCESS_GET_POINT_CREATOR = 15
    SUCCESS_GET_POINT_COMMON = 10
