# Generated by Django 2.2.4 on 2019-10-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='CurrentUser',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='EndTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='SignUpEndTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='SignUpStartTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='StartTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='joininformation',
            name='CheckTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='joininformation',
            name='JoinTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='joininformation',
            name='Status',
            field=models.IntegerField(choices=[(0, 'WaitValidate'), (1, 'Joined'), (2, 'NotChecked'), (3, 'Checked'), (4, 'Finished'), (5, 'Missed'), (6, 'Creator')]),
        ),
    ]
