# Generated by Django 2.2.4 on 2019-10-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_auto_20191030_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joininformation',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
