# Generated by Django 2.2.4 on 2019-10-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_auto_20191030_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='DataBase.User'),
        ),
    ]
