# Generated by Django 2.2.4 on 2019-10-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_auto_20191030_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='Student',
        ),
    ]
