# Generated by Django 2.2.4 on 2019-10-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0005_remove_education_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Type',
            field=models.CharField(max_length=30),
        ),
    ]
