# Generated by Django 2.2.4 on 2019-10-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_auto_20191030_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='OpenID',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
