# Generated by Django 2.2.4 on 2019-10-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0007_auto_20191030_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='ID',
        ),
        migrations.AddField(
            model_name='education',
            name='id',
            field=models.AutoField(auto_created=True, default=9, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
