# Generated by Django 2.2.4 on 2019-10-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_auto_20191030_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='id',
        ),
        migrations.AddField(
            model_name='education',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='Student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='DataBase.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='Type',
            field=models.CharField(choices=[('U', 'Undergraduate'), ('M', 'Master'), ('D', 'Doctor')], max_length=30),
        ),
    ]
