# Generated by Django 2.2.4 on 2019-10-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0009_auto_20191030_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Education', to='DataBase.User'),
        ),
    ]
