# Generated by Django 2.2.4 on 2019-10-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0010_auto_20191030_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to='DataBase.User'),
        ),
    ]
