# Generated by Django 2.2.4 on 2019-10-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0012_auto_20191031_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Member',
        ),
    ]
