# Generated by Django 2.2.4 on 2019-11-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0013_remove_activity_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Session',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='OpenID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
