# Generated by Django 2.2.4 on 2019-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0014_auto_20191102_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppId', models.CharField(max_length=100)),
                ('SecretId', models.CharField(max_length=100)),
            ],
        ),
    ]
