# Generated by Django 2.2.4 on 2019-11-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0015_globalvariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SessionKey',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
