# Generated by Django 2.2.4 on 2019-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0016_user_sessionkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='RequestID',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
