# Generated by Django 2.2.4 on 2019-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0017_user_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Type',
            field=models.CharField(max_length=30),
        ),
    ]
