# Generated by Django 2.2.4 on 2019-11-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0018_auto_20191107_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='GlobalRule',
            field=models.IntegerField(choices=[(0, 'AcceptAll'), (1, 'AuditAll'), (2, 'AuditOther'), (3, 'RejectOther')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joininformation',
            name='JoinReason',
            field=models.CharField(default=0, max_length=310),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdvancedRule',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MinStartYear', models.IntegerField()),
                ('MaxStartYear', models.IntegerField()),
                ('Department', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
                ('ActivityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdvancedRule', to='DataBase.Activity')),
            ],
        ),
    ]
