# Generated by Django 2.2.4 on 2019-11-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0019_auto_20191114_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='advancedrule',
            name='EducationType',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='GlobalRule',
            field=models.IntegerField(choices=[(0, 'Accept'), (1, 'Audit'), (2, 'Reject')]),
        ),
        migrations.AlterField(
            model_name='advancedrule',
            name='Type',
            field=models.ImageField(choices=[(0, 'Accept'), (1, 'Audit'), (2, 'Reject')], upload_to=''),
        ),
    ]
