# Generated by Django 2.2.4 on 2019-11-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0021_auto_20191115_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='CreateTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joininformation',
            name='SubmitTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
