# Generated by Django 2.2.4 on 2019-11-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0022_auto_20191116_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AvatarURL',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
