# Generated by Django 2.2.4 on 2019-11-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0023_user_avatarurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Valid',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
