# Generated by Django 2.2.4 on 2019-11-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0024_user_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Status',
        ),
        migrations.AddField(
            model_name='activity',
            name='Description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='StatusCheck',
            field=models.IntegerField(choices=[(0, 'Before'), (1, 'Continue'), (2, 'Paused'), (3, 'Stopped')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='StatusGlobal',
            field=models.IntegerField(choices=[(0, 'Except'), (1, 'Normal'), (2, 'Finish')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='StatusJoin',
            field=models.IntegerField(choices=[(0, 'Before'), (1, 'Continue'), (2, 'Paused'), (3, 'Stopped')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='Tags',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joininformation',
            name='Role',
            field=models.IntegerField(choices=[(0, 'Commoner'), (1, 'Manager'), (2, 'Creator')]),
        ),
        migrations.AlterField(
            model_name='joininformation',
            name='Status',
            field=models.IntegerField(choices=[(0, 'WaitValidate'), (1, 'Joined'), (2, 'Checked'), (3, 'Finished'), (4, 'FinishedWithoutCheck'), (5, 'Abnormal'), (6, 'Refused')]),
        ),
    ]
