# Generated by Django 2.2.4 on 2019-12-05 10:16

import DataBase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0025_auto_20191130_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, upload_to=DataBase.models.GeneratePictureURL)),
            ],
        ),
    ]
