# Generated by Django 2.2.4 on 2019-12-05 10:43

import DataBase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0026_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='CreateTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='Image',
            field=models.ImageField(upload_to=DataBase.models.GeneratePictureURL),
        ),
    ]
