# Generated by Django 2.2.4 on 2019-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0027_auto_20191205_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ImageURL',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
