# Generated by Django 2.2.4 on 2019-12-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0028_activity_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInformation',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SubmitTime', models.IntegerField()),
                ('Reason', models.CharField(max_length=310)),
                ('ActivityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReportList', to='DataBase.Activity')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReportList', to='DataBase.User')),
            ],
        ),
    ]
