# Generated by Django 2.2.4 on 2019-12-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0029_reportinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('OpenID', models.CharField(max_length=100, unique=True)),
                ('Session', models.CharField(max_length=100)),
            ],
        ),
    ]
