# Generated by Django 2.2.4 on 2019-12-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0030_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Code',
            field=models.CharField(default='UNDEFINED', max_length=100),
        ),
    ]
