# Generated by Django 2.2.4 on 2019-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0031_activity_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('Session', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
