# Generated by Django 2.2.4 on 2019-12-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0034_auto_20191209_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalvariables',
            name='AccessToken',
            field=models.CharField(default='UNDEFINED', max_length=100),
        ),
    ]
