# Generated by Django 2.2.4 on 2020-01-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0036_auto_20191221_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ExtraData',
            field=models.CharField(default='', max_length=400),
        ),
    ]
